"""
Figure 8. Does the persistence-resistance contrast survive recalibration?

Run:  python -m src.experiments.exp05_boccarella_recalibrated   (first)
      python -m src.figures.fig09_boccarella_recalibrated

Boccarella et al. (2026, doi:10.1093/molbev/msag180) report that populations with
low persistence evolve higher final resistance than populations with high
persistence. The contrast is generated by simulating two chosen persistence
levels, 0.8 and 5e-5.

Their own supplementary survival data implies different values: about 9.6e-4 for
the low-persistence condition, nineteen times what was simulated, and a value the
model cannot reach for the high-persistence condition, where the observed
survival exceeds the model's ceiling by 3.7-fold.

Their simulation is run unmodified at both. The answer is that the contrast
survives: it does not weaken, it widens slightly. The conclusion is a property of
the regime the persistence level sits in, not of the particular value chosen, and
both values sit in the same regime.

Because alpha is not identifiable from survival data, the implied values are not
estimates of a true persistence level. They are the values consistent with the
observed survival under the authors' own pharmacodynamic assumptions.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu

from . import style as st

ROOT = st.ROOT
T = ROOT / "results" / "tables"

SCEN_LABEL = {"authors": "as published", "implied": "implied by their data"}
ARM_COLOR = {"high": st.BLUE, "low": st.ORANGE}
THEIR_PUBLISHED = {"high": 9.21, "low": 18.63}   # medians, 12.5 ug/mL, their Fig 3
THEIR_NEVER = {"high": 2.6, "low": 0.6}          # percent ending at MIC 2


def build():
    st.apply()
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D
    mpl.rcParams["figure.constrained_layout.use"] = False

    rep = pd.read_csv(T / "exp05_replicates.csv")
    summ = pd.read_csv(T / "exp05_summary.csv")
    con = pd.read_csv(T / "exp05_contrast.csv")

    fig = plt.figure(figsize=(7.4, 6.4))
    gs = fig.add_gridspec(2, 2, height_ratios=[1.25, 1.0], left=0.095,
                          right=0.985, top=0.885, bottom=0.185,
                          hspace=0.68, wspace=0.32)
    ax_a = fig.add_subplot(gs[0, :])
    ax_b = fig.add_subplot(gs[1, 0])
    ax_c = fig.add_subplot(gs[1, 1])

    # ------------------------------- A: final MIC among evolved populations --
    xpos, tlab, group_mid = [], [], []
    x, k = 0, 0
    for scen in ("authors", "implied"):
        start = x
        for arm in ("high", "low"):
            g = rep[(rep.scenario == scen) & (rep.arm == arm) & (~rep.extinct)]
            v = g.loc[g.final_mic > 2.001, "final_mic"].to_numpy()
            jit = (np.random.default_rng(k).random(v.size) - 0.5) * 0.30
            ax_a.plot(x + jit, v, "o", color=ARM_COLOR[arm], ms=4.6,
                      mec=st.SURFACE, mew=0.5, alpha=0.82, zorder=4)
            med = float(np.median(v))
            ax_a.plot([x - 0.30, x + 0.30], [med, med], color=st.INK, lw=2.4,
                      zorder=6)
            ax_a.text(x + 0.36, med, f"{med:.1f}", ha="left", va="center",
                      fontsize=7.4, color=st.INK, fontweight="semibold",
                      zorder=7)
            ax_a.plot([x - 0.34, x + 0.34], [THEIR_PUBLISHED[arm]] * 2,
                      color=st.CRITICAL, lw=1.6, ls=(0, (4, 2)), zorder=5)
            xpos.append(x)
            tlab.append(arm)
            k += 1
            x += 1
        group_mid.append((start + x - 1) / 2)
        x += 0.8

    ax_a.set_xticks(xpos)
    ax_a.set_xticklabels(tlab, fontsize=7.6)
    ax_a.set_yscale("log", base=2)
    ax_a.set_ylabel("final MIC after 12 days ($\\mu$g/mL)")
    ax_a.set_title("A  final resistance among populations that evolved",
                   fontsize=8.8)
    ax_a.grid(axis="x", visible=False)
    ax_a.set_xlim(-0.7, x - 1.1)
    for xt, scen in zip(group_mid, ("authors", "implied")):
        ax_a.text(xt, -0.145, SCEN_LABEL[scen],
                  transform=ax_a.get_xaxis_transform(), ha="center", va="top",
                  fontsize=7.6, color=st.INK_SECONDARY, fontweight="semibold")
    ax_a.legend(handles=[
        Line2D([], [], color=st.INK, lw=2.4, label="median"),
        Line2D([], [], color=st.CRITICAL, lw=1.6, ls=(0, (4, 2)),
               label="their published median"),
        Line2D([], [], color=st.BLUE, marker="o", ls="none", ms=4.6,
               label="high persistence"),
        Line2D([], [], color=st.ORANGE, marker="o", ls="none", ms=4.6,
               label="low persistence"),
    ], loc="lower center", fontsize=6.6, ncols=4, columnspacing=1.1,
        handletextpad=0.4)

    # --------------------------------------------------- B: the contrast ----
    for i, r in con.iterrows():
        ratio = float(r["ratio_low_over_high_evolved_only"])
        color = st.AQUA if r["scenario"] == "authors" else st.CRITICAL
        ax_b.bar(i, ratio, width=0.5, color=color)
        ax_b.text(i, ratio + 0.04, f"{ratio:.2f}$\\times$", ha="center",
                  va="bottom", fontsize=8.0, color=st.INK,
                  fontweight="semibold")
    ax_b.axhline(1.0, color=st.AXIS, lw=1.2)
    ax_b.text(0.985, 1.02, " no difference ",
              transform=ax_b.get_yaxis_transform(), ha="right", va="bottom",
              fontsize=6.6, color=st.INK_MUTED)
    ax_b.set_xticks(range(len(con)))
    ax_b.set_xticklabels(["as\npublished", "implied by\ntheir data"],
                         fontsize=7.2)
    ax_b.set_ylabel("median MIC, low $\\div$ high")
    ax_b.set_title("B  the contrast, on their own basis", fontsize=8.6)
    ax_b.set_ylim(0, 2.5)
    ax_b.grid(axis="x", visible=False)

    # ------------------------------- C: what their filter conditions away ---
    w = 0.36
    for i, arm in enumerate(("high", "low")):
        for j, scen in enumerate(("authors", "implied")):
            row = summ[(summ.scenario == scen) & (summ.arm == arm)]
            if row.empty:
                continue
            v = 100.0 * float(row["frac_never_evolved"].iloc[0])
            ax_c.bar(i + (j - 0.5) * w, v, width=w * 0.88,
                     color=st.AQUA if scen == "authors" else st.CRITICAL)
            ax_c.text(i + (j - 0.5) * w, v + 0.2, f"{v:.1f}", ha="center",
                      va="bottom", fontsize=7.0, color=st.INK)
        ax_c.plot([i - 0.30, i + 0.30], [THEIR_NEVER[arm]] * 2,
                  color=st.INK, lw=1.6, ls=(0, (3, 2)), zorder=6)
    ax_c.set_xticks([0, 1])
    ax_c.set_xticklabels(["high\npersistence", "low\npersistence"], fontsize=7.2)
    ax_c.set_ylabel("never evolved (% of populations)")
    ax_c.set_title("C  the quantity that basis removes", fontsize=8.6)
    ax_c.set_ylim(0, 11.5)
    ax_c.grid(axis="x", visible=False)
    ax_c.legend(handles=[
        Line2D([], [], color=st.AQUA, lw=6, label="as published"),
        Line2D([], [], color=st.CRITICAL, lw=6, label="implied"),
        Line2D([], [], color=st.INK, lw=1.6, ls=(0, (3, 2)), label="theirs"),
    ], loc="upper right", fontsize=6.5, ncols=1)

    # ------------------------------------------------------------- caption --
    sel = lambda scen: rep[(rep.scenario == scen) & (rep.arm == "low") &
                           (~rep.extinct) & (rep.final_mic > 2.001)].final_mic
    pval = float(mannwhitneyu(sel("authors"), sel("implied")).pvalue)
    n_low = int(summ.loc[summ.arm == "low", "n_all"].min())
    n_high = int(summ.loc[summ.arm == "high", "n_all"].min())

    fig.suptitle("Their conclusion survives running their own simulation at the "
                 "persistence level their data implies",
                 fontsize=10.0, fontweight="semibold", x=0.006, ha="left",
                 y=0.980)
    fig.text(0.006, 0.135,
             "Their deposited simulation run unmodified "
             "(doi:10.6084/m9.figshare.31389142, CC BY 4.0) at 12.5 $\\mu$g/mL "
             f"over 12 days, with min_bR = 2 as recorded in their own output. "
             f"{n_low} populations per low-persistence arm, {n_high} per "
             "high-persistence arm.\n"
             "A and B use the basis their own Fig_3_a-b.R plots, which filters "
             "to final MIC > 2. Raising the low-persistence level nineteen-fold "
             f"does not change its outcome (Mann-Whitney p = {pval:.2f}); the "
             "contrast widens slightly rather than closing.\n"
             "The high-persistence value is pinned at 1 because the observed "
             "survival exceeds what the model can produce at any persistence "
             "level. Alpha is not identifiable from survival data, so these are "
             "values consistent with the observed survival, not estimates.",
             fontsize=6.7, color=st.INK_MUTED, ha="left", va="top",
             linespacing=1.5)
    return fig, summ, con, pval


def main() -> int:
    fig, summ, con, pval = build()
    paths = st.save(fig, "fig09_boccarella_recalibrated")
    print(summ[["scenario", "arm", "alpha", "n_all", "median_all", "n_evolved",
                "median_evolved", "frac_never_evolved"]].to_string(
        index=False, float_format=lambda v: f"{v:,.4g}"))
    print(f"\nlow arm, 19-fold change in alpha: Mann-Whitney p = {pval:.3f}")
    for p in paths:
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
