"""
Emit the manuscript's parameter section from the code that uses the values.

Run:  python -m src.parameter_table

Writes `manuscript/generated_parameter_table.md`, which Section 2.5 of the
journal manuscript includes verbatim. Generating it means the table cannot drift
away from the values the analysis actually runs on, which is the failure mode a
hand-typed table in a Methods section invites.

Nothing here computes anything new. Every number is either read off the
dataclass or derived from it by the same function the simulations call.
"""
from __future__ import annotations

from dataclasses import fields
from pathlib import Path

from .figures import fig06_mic_mdk_plane as sig
from .inference.synthetic import SCHEDULES
from .models import mechanistic as M
from .models.parameters import LOD_CFU_ML

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "manuscript" / "generated_parameter_table.md"

N0 = 1.0e6

UNITS = {
    "r": ("Replication rate of the replicating compartment", "h⁻¹"),
    "K": ("Carrying capacity", "CFU/mL"),
    "Emax_S": ("Maximum kill rate, replicating compartment", "h⁻¹"),
    "Emax_P": ("Maximum kill rate, dormant compartment", "h⁻¹"),
    "EC50": ("Half-maximal kill concentration, replicating", "reference MIC"),
    "H": ("Hill coefficient", "—"),
    "k_SP": ("Switching rate into dormancy", "h⁻¹"),
    "k_PS": ("Resuscitation rate out of dormancy", "h⁻¹"),
    "EC50_P_ratio": ("EC50 of the dormant compartment, relative", "—"),
}
SYMBOL = {
    "r": "$r$", "K": "$K$", "Emax_S": "$E_{\\max,S}$", "Emax_P": "$E_{\\max,P}$",
    "EC50": "$EC_{50}$", "H": "$H$", "k_SP": "$k_{S\\to P}$",
    "k_PS": "$k_{P\\to S}$", "EC50_P_ratio": "$\\rho$",
}


def fmt(v: float) -> str:
    """Render a value as LaTeX maths, not as Python's float repr."""
    if v == int(v) and abs(v) < 1e4:
        return f"${int(v)}$"
    if v != 0 and (abs(v) < 1e-3 or abs(v) >= 1e4):
        mant, exp = f"{v:.6g}".split("e") if "e" in f"{v:.6g}" else (None, None)
        if mant is None:
            mant, exp = f"{v:e}".split("e")
            mant = f"{float(mant):g}"
        exp = int(exp)
        mant = f"{float(mant):g}"
        if mant == "1":
            return f"$10^{{{exp}}}$"
        # Raw string: in an ordinary f-string "\t" is a tab, not a backslash.
        return "$" + mant + r" \times 10^{" + str(exp) + "}$"
    return f"${v:g}$"


def main() -> int:
    sets = [o for n in dir(M) if isinstance(o := getattr(M, n), M.PDParams)]
    sets.sort(key=lambda s: s.r)                     # slow grower first
    names = [s.label.split(" (")[0] for s in sets]

    L = ["<!-- Generated by src/parameter_table.py. Do not edit by hand. -->", ""]
    L.append("**Table 1** Parameter values of the two illustrative sets. Values "
             "are chosen to reproduce documented qualitative behaviour and are "
             "not fitted to any dataset. The two labels denote a slow-growth and "
             "a fast-growth parameterisation; they are not claims about the named "
             "organisms.")
    L.append("")
    L.append(f"| Symbol | Meaning | Unit | {names[0]} | {names[1]} |")
    L.append("|---|---|---|---|---|")
    for f in fields(M.PDParams):
        if f.name == "label":
            continue
        meaning, unit = UNITS[f.name]
        vals = " | ".join(fmt(getattr(s, f.name)) for s in sets)
        L.append(f"| {SYMBOL[f.name]} | {meaning} | {unit} | {vals} |")

    L += ["", "Quantities derived from these values by the same functions the "
              "simulations call:", ""]
    L.append(f"| Derived quantity | {names[0]} | {names[1]} |")
    L.append("|---|---|---|")
    L.append("| MIC (reference MIC units) | "
             + " | ".join(f"{M.mic(s):.4f}" for s in sets) + " |")
    L.append(f"| Dormant fraction of the inoculum at $N_0=10^6$ | "
             + " | ".join(f"{s.persister_fraction_growing(N0):.3g}" for s in sets)
             + " |")
    L.append("| Dormant fraction at carrying capacity | "
             + " | ".join(f"{s.persister_fraction_eq:.3g}" for s in sets) + " |")

    L += ["", f"Inoculum $N_0 = 10^6$ CFU/mL and limit of detection "
              f"{LOD_CFU_ML:g} CFU/mL throughout.", ""]

    L.append("**Phenotype constructions.** The signature comparison of Section "
             "3.2 starts from the slow-growth set with the dormant fraction "
             "lowered to $k_{S\\to P} = "
             + fmt(sig.BASE.k_SP).strip("$") + "$ h⁻¹ so that the "
             "baseline is not already persistent, and applies one change at a "
             f"time: resistance multiplies $EC_{{50}}$ by "
             f"{sig.RESISTANCE_FOLD:g}, tolerance divides $r$, $E_{{\\max,S}}$ "
             f"and $E_{{\\max,P}}$ by {sig.TOLERANCE_FOLD:g}, and persistence "
             f"multiplies $k_{{S\\to P}}$ by {sig.PERSISTENCE_FOLD:g}. Duration "
             f"endpoints are evaluated at {sig.EXPOSURE_MULTIPLE:g} times each "
             "variant's own MIC.")
    L.append("")

    L.append("**Synthetic observations.** Time-kill data for the fitting "
             "analyses are generated from the state-structured model of Section "
             "2.1 at four times each "
             "set's own MIC, with additive Gaussian noise on $\\log_{10}$ CFU/mL "
             "of standard deviation 0.25 for a single plate, three replicates "
             "per time point, and observations below the limit of detection "
             "recorded as censored. The generator is seeded, so the datasets are "
             "reproducible. Sampling schedules:")
    L.append("")
    L.append("| Set | Design | Times (h) |")
    L.append("|---|---|---|")
    for short, designs in SCHEDULES.items():
        for name, sched in designs.items():
            times = ", ".join(f"{x:g}" for x in sched)
            L.append(f"| {short} | {name} | {times} |")
    L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
