"""
Write the whole paper with every mention of the organism replaced by XX.

Run:  python -m src.build_blinded_copy

Reads manuscript/PAPER_COMPLETE.md, which is the one file that holds the article,
its tables and its figure legends in reading order, and writes
manuscript/BLINDED_COPY.md.

WHAT IS REPLACED. Anything that names the organism in words: any word built on
the stem "tubercul" or "mycobacteri", the binomial and its abbreviation in either
italic or plain form, and the abbreviations TB and Mtb. A binomial collapses to a
single XX rather than two, and the italic markers around a replaced span are
dropped, because *XX* is not a species name.

WHAT IS NOT REPLACED, and this is the part to read before trusting the file. A
strain designation is not the word "tuberculosis" but it identifies the organism
just as surely, and so do the drugs, the media and the specimen types. The script
reports every one it can find, with counts, at the top of the file it writes and
on the console. Extending the list is one line; deciding what belongs on it is a
judgement about who the blinded copy is for, and that is not the script's to make.
"""
from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "manuscript" / "PAPER_COMPLETE.md"
OUT = ROOT / "manuscript" / "BLINDED_COPY.md"

MASK = "XX"

# Order matters: the two-word forms have to go before the one-word ones, or
# "Mycobacterium tuberculosis" becomes "XX XX".
RULES: list[tuple[str, str]] = [
    # italic binomials, markers and all
    (r"\*Mycobacterium\s+[a-z]+\*", "italic binomial"),
    (r"\*M\.\s*[a-z]+\*", "italic abbreviated binomial"),
    # plain binomials
    (r"\bMycobacterium\s+[a-z]+\b", "binomial"),
    (r"\bM\.\s*(?:tuberculosis|abscessus|bovis|avium|smegmatis|marinum)\b",
     "abbreviated binomial"),
    # single words, italic first so the markers go with them
    (r"\*(?:[Mm]ycobacteri\w*|[Tt]ubercul\w*)\*", "italic single word"),
    (r"\b\w*[Mm]ycobacteri\w*\b", "mycobacteri- word"),
    (r"\b\w*[Tt]ubercul\w*\b", "tubercul- word"),
    (r"\bTB\b", "TB"),
    (r"\bMtb\b", "Mtb"),
]

# Not replaced. Each of these names the organism without using its name, so the
# file says so rather than letting a reader assume the blinding is complete.
RESIDUAL: list[tuple[str, str]] = [
    (r"\bH37Rv\b", "the reference strain"),
    (r"\bBCG\b", "the vaccine strain"),
    (r"\bMGIT\b", "the mycobacterial culture system"),
    (r"\b7H9\b|\b7H10\b|\b7H11\b", "Middlebrook media"),
    (r"\brifampicin\b|\brifampin\b|\brifapentine\b", "a first-line agent"),
    (r"\bisoniazid\b", "a first-line agent"),
    (r"\bpyrazinamide\b|\bethambutol\b|\bethionamide\b", "a first-line agent"),
    (r"\bbedaquiline\b|\bpretomanid\b|\bdelamanid\b", "a newer agent"),
    (r"\bkatG\b|\brpoB\b|\binhA\b", "a resistance locus"),
    (r"\bsputum\b", "the specimen type"),
    (r"\bERA4TB\b|\bTB-?APEX\b|\bTB-?PACTS\b", "a consortium name"),
]


def blind(text: str) -> tuple[str, Counter]:
    hits: Counter = Counter()

    def sub(m: re.Match) -> str:
        hits[m.group(0)] += 1
        return MASK

    for pattern, _label in RULES:
        text = re.sub(pattern, sub, text)

    # "Mycobacterium" and "tuberculosis" separated by markup collapse to one XX;
    # so does a binomial that arrived as two separate matches.
    text = re.sub(rf"\b{MASK}(?:\s+{MASK})+\b", MASK, text)
    return text, hits


def main() -> int:
    if not SRC.exists():
        raise SystemExit(f"missing {SRC}; run src/assemble_paper.py first")
    src = SRC.read_text(encoding="utf-8")
    out, hits = blind(src)

    residual: list[tuple[str, int, str]] = []
    for pattern, note in RESIDUAL:
        found = re.findall(pattern, out, re.I)
        if found:
            shown = sorted({f if isinstance(f, str) else f[0] for f in found})
            residual.append((", ".join(shown), len(found), note))

    header = [
        "<!-- Generated by src/build_blinded_copy.py. Do not edit: edit "
        "manuscript/RATE_VS_DURATION.md and rebuild. -->",
        "",
        "> **Organism-blinded copy.** Every mention of the organism in words has "
        f"been replaced by `{MASK}`: {sum(hits.values())} substitutions over "
        f"{len(hits)} distinct spellings. The spellings themselves are not listed "
        "here, for the obvious reason; the console output of the script that "
        "wrote this file has them.",
        ">",
    ]
    if residual:
        header += [
            "> **The blinding is not complete, and here is exactly where.** These "
            "identify the organism without naming it, and were left alone because "
            "removing them changes what the paper says rather than how it says it:",
            ">",
        ]
        for shown, n, note in residual:
            header.append(f"> - `{shown}` — {n} occurrence(s), {note}")
        header += [">",
                   "> Say the word and any of these can join the list.", ""]
    else:
        header += ["> No strain name, drug name, medium or specimen type that "
                   "would identify the organism was found in the text.", ""]

    OUT.write_text("\n".join(header) + "\n" + out, encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"   {sum(hits.values())} substitutions over {len(hits)} spellings")
    for k, v in hits.most_common():
        print(f"      {k:34} {v:3}")
    if residual:
        print("   still identifying, left alone:")
        for shown, n, note in residual:
            print(f"      {shown[:40]:42} {n:3}  {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
