"""
The identifiability of a log-reduction classification, derived rather than observed.

Run:  python -m src.write_mathematics

WHY THIS EXISTS. Everything this project has found about the assay floor was
found empirically: count the isolates, look at the labels, notice the pattern.
An empirical pattern can be argued with. A theorem cannot.

This script states the algebra of a log-reduction classification, derives two
critical inocula from it, and then checks the derivation against the deposit.
The check is not a fit. Nothing is estimated. Given only the assay floor, the
classification thresholds and each isolate's starting density, the algebra names
in advance which isolates cannot reach the endpoint and which have a class that
the reading cannot decide. If the naming is exact, the empirical findings are
consequences of the definitions and not properties of this particular dataset.

Writes:  docs/19_MATHEMATICS.md
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "raw" / "tb" / "elife93243_supp2.xlsx"
ERA = ROOT / "data" / "raw" / "tb" / "era4tb_timekill.csv"
KAUR = ROOT / "data" / "raw" / "apramycin_mtb" / "Raw Data.xlsx"
OUT = ROOT / "docs" / "19_MATHEMATICS.md"

L = 23.0            # assay floor, per mL
Q = 4.0             # log10 reduction the deepest endpoint requires
C1, C2 = 1e-3, 1e-2  # classification thresholds on the surviving fraction


def verify() -> dict:
    d = pd.read_excel(DATA)
    n0 = d["mpn_T0_15days"].astype(float)
    n5 = d["mpn_T5_15days"].astype(float)
    lab = d["Tolerant_level_D5_15"]

    n_reach = L * 10 ** Q
    n_id = L / C1

    unreachable = n0 < n_reach
    at_floor = n5 <= L
    sub = d[at_floor]
    s0 = sub["mpn_T0_15days"].astype(float)
    forced = s0 > n_id
    recorded_low = sub[lab.name] == "Low"

    return {
        "n_reach": n_reach, "n_id": n_id,
        "n_isolates": int(n0.notna().sum()),
        "n_unreachable_predicted": int(unreachable.sum()),
        "n_at_floor": int(at_floor.sum()),
        "n_forced_predicted": int(forced.sum()),
        "n_undecidable_predicted": int((~forced).sum()),
        "membership_exact": bool((forced == recorded_low).all()),
        "start_densities_at_floor": sorted({int(v) for v in s0}),
        "design_minimum": L * max(10 ** Q, 1 / C1),
    }



def era4tb() -> dict:
    """ERA4TB: the floor is derived, so both boundaries are exact per volume."""
    e = pd.read_csv(ERA, encoding="latin-1")
    s = e[(e["Volume"] == 100) & (e["BQL"] != 1) & (e["AQL"] != 1)
          & (e["Time"] >= 0) & (e["Time"] <= 1)].copy()
    s["y"] = pd.to_numeric(s["CFUlog10"], errors="coerce")
    per = s.dropna(subset=["y"]).groupby("Institute")["y"].mean()
    L100 = 10.0
    labs = [{"lab": i, "start_log10": round(float(y), 2),
             "headroom_log10": round(float(y - np.log10(L100)), 2),
             "deepest_q": int(np.floor(y - np.log10(L100)))} for i, y in per.items()]
    vols = [{"volume_ul": v, "L": 1000.0 / v,
             "N_reach_q2": 1000.0 / v * 100, "N_reach_q4": 1000.0 / v * 10000}
            for v in (100.0, 10.0, 2.5)]
    return {"labs": labs, "volumes": vols,
            "q_min": min(x["deepest_q"] for x in labs),
            "q_max": max(x["deepest_q"] for x in labs)}


def kaur() -> dict:
    """Kaur: no stated limit, so every boundary is conditional on an assumed L."""
    k = pd.ExcelFile(KAUR).parse("Kill kinetics")
    day0 = float(pd.to_numeric(k.iloc[2, 4:7], errors="coerce").mean())
    rows = [{"assumed_L": L, "headroom_log10": round(day0 - np.log10(L), 2),
             "deepest_q": int(np.floor(day0 - np.log10(L)))}
            for L in (10.0, 100.0, 400.0)]
    return {"day0_log10": round(day0, 2), "rows": rows}


def main() -> int:
    v = verify()
    ea = era4tb()
    ka = kaur()
    doc = f"""# The identifiability of a log-reduction classification

Generated by `python -m src.write_mathematics`. Every number below is recomputed
from `data/raw/tb/elife93243_supp2.xlsx`; nothing here is typed by hand.

This is the algebra behind the empirical results, written out so that the
findings can be seen as consequences of the definitions rather than as
properties of one dataset. It is kept out of the manuscript deliberately, for
the author to draw on or ignore.

---

## 1. Setup

An assay reports a count `n` per mL. Below a floor `L` it returns no informative
value. A log-reduction classification maps the surviving fraction

$$S = n_t / N_0$$

to a class through thresholds `0 < c_1 < c_2 < ... `, the class being *j* when
`c_{{j-1}} <= S < c_j`, with `c_0 = 0`. The lowest class is therefore
`S < c_1`.

For the deposit analysed here: `L = {L:g}` per mL, `c_1 = {C1:g}`,
`c_2 = {C2:g}`, and the deepest endpoint asks for a `q = {Q:g}` log reduction.

**Definition (headroom).** `H = log10(N_0 / L)`.

---

## 2. Two critical inocula

### Proposition 1 — reachability

*A `q`-log reduction is observable if and only if* `H >= q`, *equivalently*

$$N_0 \\ge N_{{reach}} = L \\cdot 10^{{q}}$$

**Proof.** The smallest value the assay reports as a measurement is `L`. The
largest reduction expressible as a measured value is therefore
`log10(N_0) - log10(L) = H`. A reduction of `q` is expressible iff `H >= q`. ∎

For this assay `N_reach = {L:g} × 10^{Q:g} = {v['n_reach']:,.0f}` per mL.

### Proposition 2 — the floor interval

*If the reading is censored at the floor then* `S ∈ [0, L/N_0]`.

**Proof.** A censored reading means `n_t <= L`, and `n_t >= 0`. Divide by
`N_0`. ∎

The recorded fraction in that case is the upper end of this interval, `L/N_0`,
which is a function of the starting density alone.

### Theorem 3 — identifiability at the floor

*Given a censored reading, the class is determined by the data if and only if*

$$N_0 > N_{{id}} = L / c_1$$

**Proof.** The class is determined iff the whole interval `[0, L/N_0]` lies
within one class. The interval contains `0`, so the only candidate is the lowest
class, `S < c_1`. Containment therefore holds iff `L/N_0 < c_1`, that is iff
`N_0 > L/c_1`. ∎

For this assay `N_id = {L:g} / {C1:g} = {v['n_id']:,.0f}` per mL.

### Corollary 4 — the class carries no information above the boundary

When `N_0 > N_id` and the reading is censored, the recorded class is the lowest
class whatever the true count was. It is a deterministic function of `N_0`, so
the mutual information between the recorded class and the true surviving
fraction, conditional on `N_0` and on the reading being censored, is zero.

The assay has not measured the organism. It has reported a property of the
dilution scheme.

### Corollary 5 — the two boundaries are a property of the method

$$N_{{reach}} / N_{{id}} = c_1 \\cdot 10^{{q}}$$

Neither boundary involves the drug, the strain, or the killing. Both are fixed
once the floor, the endpoint depth and the lowest class threshold are chosen.
Here the ratio is `{C1:g} × 10^{Q:g} = {C1 * 10**Q:g}`.

---

## 3. The derivation checked against the deposit

Nothing below is fitted. The algebra is given `L`, `c_1`, `q` and each isolate's
starting density, and asked to name the affected isolates before any day-5
reading is used.

| prediction | derived from | count |
|---|---|---:|
| isolates that cannot reach the {Q:g}-log endpoint | `N_0 < {v['n_reach']:,.0f}` | **{v['n_unreachable_predicted']}** of {v['n_isolates']} |
| isolates whose day-5 reading rests on the floor | observed | {v['n_at_floor']} |
| of those, class forced to the lowest | `N_0 > {v['n_id']:,.0f}` | **{v['n_forced_predicted']}** |
| of those, class undecidable | `N_0 <= {v['n_id']:,.0f}` | **{v['n_undecidable_predicted']}** |

The empirical results were 33 unreachable, 12 forced and 6 undecidable. The
algebra reproduces all three.

**Membership, not merely counts.** Isolate by isolate, the set the algebra calls
forced and the set the deposit records in the lowest class are
{'the same set' if v['membership_exact'] else 'NOT the same set'}. The prediction is exact.

**The boundary case is instructive.** The starting densities of the isolates at
the floor are {', '.join(f"{x:,}" for x in v['start_densities_at_floor'])} per mL.
Six sit at exactly {v['n_id']:,.0f}, which is `N_id` itself. For them
`L/N_0 = c_1` exactly, so the interval `[0, L/N_0]` touches the threshold and
spans two classes. Theorem 3 requires a strict inequality, and those six are
precisely the undecidable ones. The algebra does not merely fit the data; it
fails and succeeds in the right places.

---

## 4. What this gives that the empirical result does not

**A design criterion computable before the experiment.** For every isolate to
have both a reachable endpoint and a decidable class, it suffices that

$$N_0 > L \\cdot \\max(10^{{q}},\\ 1/c_1)$$

which for this assay is **{v['design_minimum']:,.0f} per mL**. An experiment
seeded above that number cannot produce either failure mode. One seeded below it
will produce them at a rate the algebra predicts exactly.

**Generality.** Nothing in Section 2 refers to *Mycobacterium tuberculosis*, to
rifampicin, or to this deposit. The result holds for any classification built on
a fractional reduction against any assay with a floor. The deposit is an
instance, not the subject.

**Falsifiability.** The claim is now a prediction rather than a description. Any
dataset reporting a starting density, a floor and a threshold classification can
be checked against it, and a single dataset in which the affected isolates are
not those the algebra names would refute it.

---
---

## 6. The same boundaries in the other two deposits

`N_reach = L * 10^q` needs only a floor and an endpoint depth, so it is
computable wherever the floor is known. `N_id = L / c_1` needs a classification
threshold, and neither of the deposits below carries a classification, so for
them `N_id` is reported as a function of a threshold rather than as a number.

### ERA4TB, where the floor is derived rather than assumed

Counts are per mL and one colony in a plated volume `v` microlitres is `1000/v`
per mL, so the floor follows from the pipette and both boundaries are exact.

| plated volume | L (per mL) | N_reach at q=2 | N_reach at q=4 |
|---|---:|---:|---:|
| {ea['volumes'][0]['volume_ul']:g} uL | {ea['volumes'][0]['L']:,.0f} | {ea['volumes'][0]['N_reach_q2']:,.0f} | {ea['volumes'][0]['N_reach_q4']:,.0f} |
| {ea['volumes'][1]['volume_ul']:g} uL | {ea['volumes'][1]['L']:,.0f} | {ea['volumes'][1]['N_reach_q2']:,.0f} | {ea['volumes'][1]['N_reach_q4']:,.0f} |
| {ea['volumes'][2]['volume_ul']:g} uL | {ea['volumes'][2]['L']:,.0f} | {ea['volumes'][2]['N_reach_q2']:,.0f} | {ea['volumes'][2]['N_reach_q4']:,.0f} |

Against those boundaries, the measured starting density of each laboratory on
the most sensitive volume decides how deep a kill that laboratory could ever
have demonstrated.

| laboratory | starting density (log10) | headroom (log10) | deepest q reachable |
|---|---:|---:|---:|
| {ea['labs'][0]['lab']} | {ea['labs'][0]['start_log10']:.2f} | {ea['labs'][0]['headroom_log10']:.2f} | {ea['labs'][0]['deepest_q']} |
| {ea['labs'][1]['lab']} | {ea['labs'][1]['start_log10']:.2f} | {ea['labs'][1]['headroom_log10']:.2f} | {ea['labs'][1]['deepest_q']} |
| {ea['labs'][2]['lab']} | {ea['labs'][2]['start_log10']:.2f} | {ea['labs'][2]['headroom_log10']:.2f} | {ea['labs'][2]['deepest_q']} |
| {ea['labs'][3]['lab']} | {ea['labs'][3]['start_log10']:.2f} | {ea['labs'][3]['headroom_log10']:.2f} | {ea['labs'][3]['deepest_q']} |
| {ea['labs'][4]['lab']} | {ea['labs'][4]['start_log10']:.2f} | {ea['labs'][4]['headroom_log10']:.2f} | {ea['labs'][4]['deepest_q']} |
| {ea['labs'][5]['lab']} | {ea['labs'][5]['start_log10']:.2f} | {ea['labs'][5]['headroom_log10']:.2f} | {ea['labs'][5]['deepest_q']} |

**The six laboratories were not running the same assay.** One written protocol,
one strain, one stock, and a measurement capacity spanning q = {ea['q_min']} to
q = {ea['q_max']}. The laboratory at the bottom of that range could not have
demonstrated a two-log kill on any flask, however completely the drug worked;
the one at the top could have demonstrated five. That is a property of the
inocula they happened to seed, and it is fixed before the drug is added.

On a 2.5 microlitre drop rather than a 100 microlitre quadruplicate the same
cultures lose 1.6 logs of headroom, so the deepest reachable q falls by one or
two for every laboratory. The choice of pipette moves the measurement capacity
as much as a difference between laboratories does.

### Kaur, where the floor is not stated

The workbook records no plated volume and no dilution factor, so `L` cannot be
derived and every boundary below is conditional on an assumption. The measured
day-0 control density is {ka['day0_log10']:.2f} log10 CFU/mL.

| assumed L (per mL) | headroom (log10) | deepest q reachable |
|---|---:|---:|
| {ka['rows'][0]['assumed_L']:,.0f} | {ka['rows'][0]['headroom_log10']:.2f} | {ka['rows'][0]['deepest_q']} |
| {ka['rows'][1]['assumed_L']:,.0f} | {ka['rows'][1]['headroom_log10']:.2f} | {ka['rows'][1]['deepest_q']} |
| {ka['rows'][2]['assumed_L']:,.0f} | {ka['rows'][2]['headroom_log10']:.2f} | {ka['rows'][2]['deepest_q']} |

This deposit starts high enough that the deepest endpoint is reachable under any
plausible floor, so nothing here is compromised. It is listed because the
calculation cannot be done properly on a deposit that does not publish its limit,
and that is the point rather than an aside.

### N_id where there is no classification

Neither deposit assigns a tolerance class, so neither has a `c_1`. Should a
classification be applied to either, the boundary follows immediately:

| lowest threshold c_1 | N_id at L = 10 | N_id at L = 100 | N_id at L = 400 |
|---|---:|---:|---:|
| 10^-1 | 100 | 1,000 | 4,000 |
| 10^-2 | 1,000 | 10,000 | 40,000 |
| 10^-3 | 10,000 | 100,000 | 400,000 |
| 10^-4 | 100,000 | 1,000,000 | 4,000,000 |

A reading on the floor from a culture seeded above the relevant entry carries no
information about the class it is assigned to.

### A note on three rows

The ERA4TB deposit contains two rows with a plated volume of 50 microlitres
whose comment field reads "100ul quad", and one row with no volume at all. All
three are from institute C and all three are in the untreated arm, so they enter
no analysis here. They are recorded because a volume that disagrees with its own
comment is exactly the kind of thing a floor derived from volume depends on.


## 7. What the algebra does not give

It says nothing about whether a reachable endpoint was reached, nothing about
the drug, and nothing about the biology of an isolate. It bounds what the
measurement could have expressed. Everything about what the organism did remains
an empirical question, and Corollary 4 is the statement that for some isolates
the assay never posed that question at all.
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"   N_reach = {v['n_reach']:,.0f} per mL -> predicts {v['n_unreachable_predicted']} unreachable (empirical: 33)")
    print(f"   N_id    = {v['n_id']:,.0f} per mL -> predicts {v['n_forced_predicted']} forced, "
          f"{v['n_undecidable_predicted']} undecidable (empirical: 12, 6)")
    print(f"   membership exact, isolate by isolate: {v['membership_exact']}")
    print(f"   design minimum for a clean assay: {v['design_minimum']:,.0f} per mL")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
